add new
Juarpla/handcrafted-haven pull request #55
Opened 2024-10-17 04:27 UTC by alexanderchagua

add dashboard

2024-10-18 10:10 UTC, Juarpla requested changes
✅ I have noticed that there are comments in Spanish, so that we can all understand it would be good to change it to English.

✅ I noticed that you formatted almost the entire code, to avoid errors it would be better to do that in a separate PR, but since you already executed it, it will just be a matter of testing that everything is working well.

✅ Since it is not possible to distinguish your real changes, it would be suggested that you describe them in the PR conversation so we can identify which files your real changes are in.

2024-10-18 10:10 UTC, Juarpla commented on src/app/components/SatisfiedClients.tsx
You have comments in spanish, may you change them to english or delete them

2024-10-18 10:21 UTC, Juarpla commented on src/app/components/SatisfiedClients.tsx
🙋 
Likewise, it is not possible to test the dashboard, since there is no access to it, if the environment variables have changed, it would be good to send them to the MS Teams group to test them.

![Screenshot 2024-10-18 at 5 17 25 AM](https://github.com/user-attachments/assets/d669a45a-c609-4064-b2eb-54c8c8bbc605)

2024-10-19 23:49 UTC, MacPerkins approved these changes
Everything looks good to merge and has been tested to ensure it functions properly.

2024-10-20 00:05 UTC, MacPerkins approved these changes
Looks good

2024-10-21 06:37 UTC, Juarpla approved these changes
Resolved conflict correctly 🫡

2024-10-21 06:38 UTC, merged